apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: notes-app
type: Opaque
data:
  # Mot de passe: "notespassword123" encod√© en base64
  POSTGRES_PASSWORD: bm90ZXNwYXNzd29yZDEyMw==
