apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: notes-app
type: Opaque
data:
  # Base de données PostgreSQL
  # Valeur: postgresql://notesuser:notespassword123@postgres:5432/notesdb
  DATABASE_URL: cG9zdGdyZXNxbDovL25vdGVzdXNlcjpub3Rlc3Bhc3N3b3JkMTIzQHBvc3RncmVzOjU0MzIvbm90ZXNkYg==
  
  # Token API pour sécuriser les endpoints
  # Valeur: mon-super-token-secret-123
  API_TOKEN: bW9uLXN1cGVyLXRva2VuLXNlY3JldC0xMjM=
